In [1]:
import pandas as pd

In [9]:
## ЗАДАНИЕ 1 ##

data = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')

df = pd.DataFrame(data.merge(movies))

def class_rating(rating):
    if rating <= 2:
        return 'низкий рейтинг'
    if 2 < rating <= 4:
        return 'средний рейтинг'
    if 4.5 <= rating <= 5:
        return 'высокий рейтинг'

df['class'] = df['rating'].apply(class_rating)
df.head(250)

,userId,movieId,rating,timestamp,title,genres,class
0,1,296,5.0,1147880044,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг
1,3,296,5.0,1439474476,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг
2,4,296,4.0,1573938898,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг
3,5,296,4.0,830786155,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг
4,7,296,4.0,835444730,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг
...,...,...,...,...,...,...,...
245,526,296,4.0,874929742,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг
246,528,296,4.0,845381208,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг
247,529,296,5.0,1009373228,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг
248,530,296,4.0,838201498,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг
249,532,296,5.0,828444000,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг

In [34]:
## ЗАДАНИЕ 2 ##

geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

keywords = pd.read_csv('keywords.csv')

def region(value):
    for region, location in geo_data.items():
        for city in location:
            if city in value.lower():                
                return region
    return 'undefined'


keywords['region'] = keywords.keyword.apply(region)

keywords[ keywords['region'] == 'Северо-Запад' ].head()

                                                keyword   shows        region
370                            авито ру санкт петербург  425134  Северо-Запад
564                           погода в санкт петербурге  292489  Северо-Запад
1236                               банк санкт петербург  174375  Северо-Запад
1346                                    санкт петербург  144232  Северо-Запад
2121  электронный дневник санкт петербургского образ...   94835  Северо-Запад

In [10]:
## ЗАДАНИЕ 3 ##

def check_year(movie):
    for year in list(range(1950,2011)):
        if str(year) in movie:
            return year
    return 1900

df['year'] = df['title'].apply(check_year)

df.head(10)

,userId,movieId,rating,timestamp,title,genres,class,year
0,1,296,5.0,1147880044,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994
1,3,296,5.0,1439474476,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994
2,4,296,4.0,1573938898,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг,1994
3,5,296,4.0,830786155,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг,1994
4,7,296,4.0,835444730,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,средний рейтинг,1994
5,8,296,5.0,890489713,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994
6,10,296,4.5,1227571308,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994
7,12,296,5.0,1119354604,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994
8,13,296,5.0,1238029599,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994
9,14,296,5.0,1506208897,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,высокий рейтинг,1994

In [11]:
df.groupby('year')['rating'].mean().sort_values(ascending=False).head()

year
1957    3.999492
1954    3.985693
1972    3.956477
1962    3.929445
1952    3.895315
Name: rating, dtype: float64