In [19]:
pip install git+https://github.com/nlpub/pymystem3

Collecting git+https://github.com/nlpub/pymystem3
  Cloning https://github.com/nlpub/pymystem3 to c:\users\semen\appdata\local\temp\pip-req-build-fbnqvghq
Requirement already satisfied (use --upgrade to upgrade): pymystem3==0.2.0 from git+https://github.com/nlpub/pymystem3 in c:\users\semen\anaconda3\lib\site-packages
Requirement already satisfied: requests in c:\users\semen\anaconda3\lib\site-packages (from pymystem3==0.2.0) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\semen\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\semen\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\semen\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\semen\anaconda3\lib\site-packages (from requests->pymystem3==0.2.0) (2019.11.28)
Building wheels for collected packages: pymystem3
  Building wheel for pymystem3 (setup.py): started
  Building wheel for pymystem3 (setup.py): finished with status 'done'
  Created wheel for pymystem3: filename=pymystem3-0.2.0-py3-none-any.whl size=8033 sha256=7085b7fa00d93578e0f1b9a3f71ea27274b79eaa2ec403ded9dcf128fda4ed81
  Stored in directory: C:\Users\semen\AppData\Local\Temp\pip-ephem-wheel-cache-g81eivnz\wheels\72\92\6b\9521f1a0b0f77ec13f07bf5f87c50c531b1d8686cf8ad48b43
Successfully built pymystem3
Note: you may need to restart the kernel to use updated packages.

  Running command git clone -q https://github.com/nlpub/pymystem3 'C:\Users\semen\AppData\Local\Temp\pip-req-build-fbnqvghq'

In [20]:
import pandas as pd

from pymystem3 import Mystem

In [9]:
## ЗАДАНИЕ 1 ##

log = pd.read_csv('visit_log.csv', sep=';')

# если источник traffic_source равен yandex или google, то в source_type ставится organic
# для источников paid и email из России - ставим ad
# для источников paid и email не из России - ставим other
# все остальные варианты берем из traffic_source без изменений

log.loc[log['traffic_source'].isin(['yandex' ,'google']), 'source_type'] = 'organic'
log.loc[(log['traffic_source'] == 'paid') & (log['region'] == 'Russia'), 'source_type'] = 'ad'
log.loc[(log['traffic_source'] == 'paid') & (log['region'] != 'Russia'), 'source_type'] = 'other'
log.loc[pd.isnull(log['source_type']), 'source_type'] = log['traffic_source']
log

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,other
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,ad
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,email

In [15]:
## ЗАДАНИЕ 2 ##

# /, затем 8 цифр, затем дефис

urls = pd.read_csv('URLs.txt')
urls = urls[urls['url'].str.contains('/\d{8}-')]
urls

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

In [26]:
## ЗАДАНИЕ 3 ##

data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

def my_lem(row):
    m = Mystem()
    lemmas = m.lemmatize(row['keyword'])
    return ' '.join(lemmas).strip()
     
data['lemmas'] = data.apply(my_lem, axis=1)

data

                 keyword   shows                     lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль
1        доллары в рубли  114173         доллар   в   рубль
2  100 долларов в рублях   97534   100   доллар   в   рубль
3             курс рубля   53546               курс   рубль